/*create db*/
CREATE DATABASE oi24o2
/*create tables*/
CREATE TABLE `oi24o2`.`auto` (`ID` INT NOT NULL AUTO_INCREMENT , `CARMODELL` VARCHAR(30) NOT NULL , `DOORS` INT NOT NULL , `PICKUPDATE` DATE NOT NULL , `DROPOFFDATE` DATE NOT NULL , `RENTERNAME` VARCHAR(80) NOT NULL , `PRICE` INT NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
